services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"

  projectmanager:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/my_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
