services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"

  project-manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      URL: jdbc:postgresql://db:5432/my_db
      USERNAME_VALUE: my_user
      PASSWORD: postgres
    depends_on:
      - db
